version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      eslint:
        applies-to: version-updates
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
